// Extracts the Lucide icons Findex uses into one PHP map, so the app has no
// runtime dependency on node_modules. Re-run after editing NAMES.
import { readFileSync, writeFileSync } from 'node:fs';

const NAMES = [
    // navigation + chrome
    'search', 'map-pin', 'arrow-right', 'arrow-left', 'chevron-down', 'chevron-right',
    'check', 'x', 'plus', 'minus', 'info', 'external-link', 'sliders-horizontal', 'pencil',
    // the verticals
    'arrow-left-right', 'shield-check', 'plane', 'plane-takeoff', 'house',
    'landmark', 'graduation-cap', 'car', 'banknote', 'credit-card',
    // comparison vocabulary
    'scale', 'bell', 'badge-check', 'star', 'trending-up', 'percent', 'tag',
    'clock', 'calendar-days', 'users', 'bed-double', 'utensils', 'luggage',
    'wallet', 'lock', 'mail', 'lightbulb', 'file-text', 'map', 'phone', 'globe',
    'building-2', 'circle-check', 'user', 'id-card', 'sparkles', 'hand-coins', 'ticket', 'sun',
];

const out = {};
for (const name of NAMES) {
    const svg = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, 'utf8');
    const body = svg
        .replace(/<svg[^>]*>/, '')
        .replace('</svg>', '')
        .replace(/<!--.*?-->/gs, '')
        .replace(/\n\s*/g, '')
        .trim();
    if (!body) throw new Error(`empty icon: ${name}`);
    out[name] = body;
}

const php = `<?php

// GENERATED by tools/build-icons.mjs - do not edit by hand.
// Lucide (ISC). One icon family for the whole product; add a name to NAMES
// there and re-run \`npm run icons\`.
return [
${Object.entries(out).map(([k, v]) => `    '${k}' => '${v.replace(/'/g, "\\'")}',`).join('\n')}
];
`;
writeFileSync('resources/icons/lucide.php', php);
console.log(`${NAMES.length} icons -> resources/icons/lucide.php`);
